{{/*
Copyright © 2018 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: BSD-2-Clause
*/}}
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "fluentd-router.fullname" . }}
  labels:
    app: {{ template "fluentd-router.name" . }}
    chart: {{ template "fluentd-router.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources:
  - namespaces
  verbs:
  - patch
- apiGroups: ["policy"]
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ template "fluentd-router.fullname" . }}
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "fluentd-router.name" . }}
    chart: {{ template "fluentd-router.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "fluentd-router.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "fluentd-router.fullname" . }}
subjects:
- name: {{ template "fluentd-router.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
{{- end }}
