{{/*
Copyright © 2018 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: BSD-2-Clause
*/}}
{{- if and .Values.prometheus.enabled .Values.prometheus.serviceMonitor.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fluentd-router.fullname" . }}
  labels:
    app: {{ template "fluentd-router.name" . }}
    chart: {{ template "fluentd-router.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "fluentd-router.name" . }}
    release: {{ .Release.Name }}
  ports:
    - name: prometheus
      port: 24231
      targetPort: prometheus
      protocol: TCP
{{- end }}
